name: Ruff Checks

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv with ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
    - name: Analysing the code with ruff
      run: |
        uv run ruff check
